export const TYPES = {
    LISTAR_PROFESIONALES: "LISTAR_PROFESIONALES",
    OBTENER_PROFESIONAL: "OBTENER_PROFESIONAL",
    REGISTRAR_PROFESIONAL: "REGISTRAR_PROFESIONAL",
    ACTUALIZAR_PROFESIONAL: "ACTUALIZAR_PROFESIONAL",
    ELIMINAR_PROFESIONAL: "ELIMINAR_PROFESIONAL",
    ACTUALIZAR_LISTA: "ACTUALIZAR_LISTA"

}